# Название: modules/pro-users.nix — Базовые пользователи и sudo правила
# Summary (EN): Declare standard user accounts and sudo policy for the fleet
# Цель:
#   Создать стандартный набор пользовательских учётных записей и централизовать
#   политику sudo для управляемых хостов, чтобы упростить администрирование.
# Контракт:
#   Опции: нет специфичных опций кроме импорта модуля; поведение задаётся внутри.
#   Побочные эффекты: добавляет users.users для учёток az, za, la, bo; создаёт
#   группы pro, netdev и pro-agent; задаёт security.sudo.extraRules.
# Предпосылки / Риски:
#   NOPASSWD в sudo упрощает управление, но повышает риск при компрометации
#   учётной записи — внимательно следите за списком пользователей и аудитом.
# Как проверить (Proof):
#   Проверить наличие пользователей: `id az` на хосте или `nix eval .#...`;
#   Поведение sudo: `sudo -l -U az` после сборки.
# Last reviewed: 2026-05-03
{ config, pkgs, lib, emacsPkg ? pkgs.emacs, opencodeBwrapModule ? null, ... }:

{
  # Почему вынесено в опцию: SSH-ключ — персональный; хардкодить его в
  # `modules/` = коммитить публичный ключ в общий репо. Опция позволяет
  # прописать ключ в `local.nix` (в .gitignore, machine-local) или в
  # `hosts/<host>/configuration.nix` (если разные ключи на разных хостах).
  # Default: пустой список — без ключей `az`/`za`/`la`/`bo` не смогут
  # зайти по SSH, остаётся только путь GPG pro-peer-sync-keys
  # (см. modules/pro-peer.nix).
  options.pro.ssh.authorizedKeys = lib.mkOption {
    type = lib.types.listOf lib.types.str;
    default = [ ];
    example = [ "ssh-rsa AAAAB3NzaC1yc2E...== user@host" ];
    description = ''
      SSH public keys authorized for az/za/la/bo. Один и тот же набор
      добавляется в `~/.ssh/authorized_keys` каждого из четырёх
      аккаунтов. Per-user override (например, az — admin, la — readonly)
      — через host-level `users.users.<name>.openssh.authorizedKeys.keys`.

      Как прописать:
        - local.nix (предпочтительно, ключ не попадает в публичный репо):
            pro.ssh.authorizedKeys = [ "ssh-rsa AAAAB3... user@host" ];
        - hosts/<host>/configuration.nix (если ключ machine-specific).
    '';
  };

  config = {

  # Создаём стандартные пользовательские учётные записи для этого коллектива.
  # Формируем список через listToAttrs для компактности конфигурации.
  users.users = builtins.listToAttrs (map (name: {
    inherit name;
    value = {
      isNormalUser = true;
      description = name;
      # Группы: необходимы для доступа к сетевым, вводным и dev-ресурсам.
      extraGroups = [ "networkmanager" "wheel" "bluetooth" "docker" "input" "uinput" "pro" "pro-agent" ];
      # Минимальный набор программ в пользовательском профиле.
      packages = with pkgs; [ git ];
      # Ключи читаются из `pro.ssh.authorizedKeys` (см. опцию выше);
      # default — пустой массив, заполняется через `local.nix`.
      openssh.authorizedKeys.keys = config.pro.ssh.authorizedKeys;
    };
  }) [ "az" "za" "la" "bo" ]);

  # Локальная служебная группа для дополнительных прав/доступов, используемых
  # внутри репозитория и вспомогательных сервисов.
  users.groups.pro = { };
  # Группа netdev требуется некоторыми D-Bus policy файлами (например, avahi).
  # Если группы нет, dbus может сорвать reload во время `nixos-rebuild switch`.
  users.groups.netdev = { };

  # Global umask: applied to all login sessions for every user (including
  # system accounts like `syncthing` and pro group members az/za/la/bo).
  # Default is 077, which strips group/world write on new files. We use 0002
  # so files created via `cp`, shell redirect, or GUI file managers in shared
  # directories (e.g. /srv/syncthing/share) are group-writable by default.
  # Combined with setgid + the `pro` group on shared paths, every pro member
  # gets transparent read+write access without manual `chmod g+rw` after copy.
  # Safe here because pro group is intentionally the shared-write group;
  # host-local secrets in $HOME remain protected by users.users.<name>.home
  # mode (typically 0700/0750).
  security.loginDefs.settings.UMASK = "0002";
  # /etc/login.defs only controls `useradd` defaults; running shells
  # inherit umask from the parent process. NixOS launches user shells
  # with umask 0022 by default (see /etc/profile generated by activation).
  # Force 0002 in interactiveShellInit so terminal emulators, scripts run
  # from desktop launchers, and SSH sessions all see group-writable files.
  # Idempotent and silent when already 0002.
  programs.bash.interactiveShellInit = lib.mkAfter ''
    # pro-nix: enforce group-writable default umask for all pro members.
    [ "$(umask)" != "0002" ] && umask 0002
  '';

  # Политика sudo: явно включаем sudo и разрешаем пользователям группы wheel
  # получать права без запроса пароля. Это удобная политика для управляемых
  # машин в пределах этой коллекции хостов; при необходимости хост может
  # переопределить эту настройку.
  security.sudo.enable = true;
  security.sudo.wheelNeedsPassword = false;

  # Дополнительные правила sudo: разрешаем перечисленным пользователям запуск
  # любых команд без пароля (NOPASSWD). Это декларация доступа, следует
  # применять осторожно и контролировать список учёток.
  users.groups.pro-agent = {};
  # Make sudo extra rules additive so hosts can augment/restrict them.
  security.sudo.extraRules = lib.mkDefault ([
    {
      users = [ "az" "za" "la" "bo" ];
      commands = [ { command = "ALL"; options = [ "NOPASSWD" ]; } ];
    }
  ]);

  # Настройки home-manager, передаём инъекции аргументов и включаем
  # использование пользовательских пакетов.
  home-manager = {
    extraSpecialArgs = { inherit pkgs emacsPkg; } // lib.optionalAttrs (opencodeBwrapModule != null) { inherit opencodeBwrapModule; };
    backupFileExtension = "backup";
    useUserPackages = true;
  };

  # Привязка профиля окружения (NixOS-eval) к HM-опции pro.emacs.gui.enable.
  # Это единственное место, где NixOS-опция (pro.profiles.exwmMinimal.enable)
  # превращается в HM-опцию (home-manager.users.<name>.pro.emacs.gui.enable):
  # прямое присваивание в HM-eval невозможно — `pro.profiles` не определена
  # в home-manager, и `osConfig` в release-25.11 не пробрасывается через
  # extraSpecialArgs автоматически. Установка здесь означает, что
  # ~/.config/pro/exwm-session (генерируется emacs/exwm.nix, гейт cfg.gui.enable)
  # появляется только на хостах с exwmMinimal-профилем.
  home-manager.users = builtins.listToAttrs (map (name: {
    inherit name;
    value = { pro.emacs.gui.enable = config.pro.profiles.exwmMinimal.enable or false; };
  }) [ "az" "za" "la" "bo" ]);

  };  # config =

  # `imports` — top-level опция, нельзя класть внутрь `config = { ... }`.
  # Подключает HM-профили, pro-agent-configs и т.п. для всех пользователей.
  imports = [ ./pro-users-nixos.nix ];
}
