# Название: modules/pro-telegram.nix — Telegram Desktop + telega (Emacs) через Tor
# Summary (EN): Telegram clients (TDesktop, telega.el) routed через Tor SOCKS5
#                 когда Tor доступен на 127.0.0.1:9050 (стандартный local
#                 Tor daemon, либо upstream SOCKS5 от Android-tethering
#                 через WiFi/cellular).
#
# Цель:
#   Telegram MTProto протокол ходит напрямую (без proxy supportа в
#   mainline tdlib). Поэтому единственный practical path к анонимизации —
#   системный SOCKS5 proxy (Tor) через `torsocks`. Модуль:
#   1. Регистрирует `tdesktop-tor-launch` user-desktop entry, заменяющий
#      стандартный `telegram-desktop` на tor-conditional.
#   2. Регистрирует D-Bus / socket активацию для `telega-server` через
#      `telega-server-tor-launch` (через torsocks).
#   3. Обеспечивает `torsocks` пакет в `systemPackages`.
#   4. Опционально — даунгрейд до прямого подключения через
#      `pro.telegram.disableTor = true` (для отладки / non-Tor зон).
#
# Контракт:
#   Опции:
#     pro.telegram.useTor                  — default true, основной switch.
#     pro.telegram.disableTor               — default false, explicit disable.
#     pro.telegram.socksHost/Port           — default 127.0.0.1:9050.
#     pro.telegram.enableTdesktop           — default true (independent toggle).
#     pro.telegram.enableTelegaServer       — default true (independent toggle).
#     pro.telegram.enableTorService         — default true (boot-time check).
#   Побочные эффекты:
#     - Adds wrapper scripts `tdesktop-tor-launch` и `telega-server-tor-launch`
#       в `environment.systemPackages` (через writeShellScriptBin).
#     - Регистрирует systemd.service `pro-telegram-tor.service` (boot-time check).
#     - Регистрирует systemd.user.service `tdesktop-tor.service` (per-session autostart).
#
# Как проверить:
#   ./scripts/check-tor-socks.sh                 # exit 0 = Tor OK
#   ./scripts/tdesktop-tor-launch.sh --check    # exit 0 = wrapped launch path
#   ./scripts/telega-server-tor-launch.sh --check
#   nix-instantiate --eval .#cf19.config.pro.telegram.{useTor,enableTdesktop,enableTelegaServer}
#
# Соответствие существующему:
#   - `services.tor` (pro-privacy.nix) стартует Tor с SOCKSPort=9050.
#   - Пользователь может вытащить WiFi на телефон и пользоваться его Tor
#     (Orbot/TorVPN), пробросив SOCKS5 через `socat` или `tun2socks` локально.
{ config, pkgs, lib, ... }:

let
  cfg = config.pro.telegram;

  # Wrapper scripts — генерируются в Nix store, доступны как
  # $PATH entries через environment.systemPackages.
  tdesktop-launch = pkgs.writeShellScriptBin "tdesktop-tor-launch" ''
    #!${pkgs.bash}/bin/bash
    # Auto-generated by pro-telegram.nix. Wraps telegram-desktop,
    # routing через torsocks when Tor SOCKS5 is reachable.
    HOST="''${PRO_TELEGRAM_TOR_HOST:-127.0.0.1}"
    PORT="''${PRO_TELEGRAM_TOR_PORT:-9050}"
    if ${./../scripts/check-tor-socks.sh} --host "$HOST" --port "$PORT" >/dev/null 2>&1 \
      && command -v torsocks >/dev/null 2>&1; then
      echo "[tdesktop-tor] Tor available at $HOST:$PORT, launching via torsocks" >&2
      exec torsocks telegram-desktop "$@"
    fi
    echo "[tdesktop-tor] Tor unavailable at $HOST:$PORT, direct launch" >&2
    exec telegram-desktop "$@"
  '';

  telega-server-launch = pkgs.writeShellScriptBin "telega-server-tor-launch" ''
    #!${pkgs.bash}/bin/bash
    # Auto-generated by pro-telegram.nix. Wraps telega-server (tdlib-bridge)
    # через torsocks когда Tor SOCKS5 доступен. Используется через
    # telega.el: после (require 'telega) telega-server-command подменяется
    # на этот wrapper (см. pro-chat.el).
    HOST="''${PRO_TELEGRAM_TOR_HOST:-127.0.0.1}"
    PORT="''${PRO_TELEGRAM_TOR_PORT:-9050}"
    TG_PORT="''${PRO_TELEGA_PORT:-6056}"
    if ${./../scripts/check-tor-socks.sh} --host "$HOST" --port "$PORT" >/dev/null 2>&1 \
      && command -v torsocks >/dev/null 2>&1; then
      echo "[telega-server-tor] Tor available at $HOST:$PORT, launching via torsocks" >&2
      exec torsocks telega-server --forward=tcp:127.0.0.1:$TG_PORT:127.0.0.1:$TG_PORT "$@"
    fi
    echo "[telega-server-tor] Tor unavailable at $HOST:$PORT, direct launch" >&2
    exec telega-server --forward=tcp:127.0.0.1:$TG_PORT:127.0.0.1:$TG_PORT "$@"
  '';

  # Systemd service: проверка Tor при boot (system-level one-shot).
  proTelegramTorService = lib.mkIf cfg.enableTorService {
    description = "Ensure Tor SOCKS5 endpoint available before telega-server runs";
    wantedBy = [ "multi-user.target" ];
    wants = [ "network-online.target" ];
    after = [ "network-online.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      SuccessExitStatus = 1;
      ExecStart = "${pkgs.bash}/bin/bash ${./../scripts/check-tor-socks.sh} -v";
    };
  };

  # Independent toggles: можно использовать только TDesktop через Tor,
  # а telega.el — нет (или наоборот). Полезно для отладки/частичной
  # анонимизации.
  enableTdesktopEffective = cfg.useTor && cfg.enableTdesktop && !cfg.disableTor;
  enableTelegaServerEffective = cfg.useTor && cfg.enableTelegaServer && !cfg.disableTor;

  # Systemd user service: autostart tdesktop-tor when user logs in.
  # Per-user, per graphical-session, with Restart=on-failure для
  # устойчивости к flapping Tor.
  tdesktopUserService = lib.mkIf enableTdesktopEffective {
    description = "Telegram Desktop with Tor proxy (auto-restart if Tor down)";
    wantedBy = [ "graphical-session.target" ];
    after = [ "graphical-session.target" ];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${tdesktop-launch}/bin/tdesktop-tor-launch";
      Restart = "on-failure";
      RestartSec = "30s";
      Environment = [
        "PRO_TELEGRAM_TOR_HOST=${cfg.socksHost}"
        "PRO_TELEGRAM_TOR_PORT=${toString cfg.socksPort}"
      ];
    };
  };
in {

  options = {
    pro.telegram = {
      useTor = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Route Telegram clients (TDesktop, telega.el) через Tor SOCKS5
          когда Tor доступен. Fallback на direct connect если Tor
          недоступен.
        '';
      };
      enableTorService = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Создать systemd unit `pro-telegram-tor.service` который
          проверяет Tor при boot (one-shot). Полезно для boot-time
          readiness-check, не зависит от Telegram services.
        '';
      };
      disableTor = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Принудительно отключить Tor-обёртки. Используется в зонах без
          Tor (например, прямой кабель в офисе) когда force-direct
          предпочтительнее.
        '';
      };
      socksHost = lib.mkOption {
        type = lib.types.str;
        default = "127.0.0.1";
        description = ''
          SOCKS5 proxy host. По умолчанию — локальный Tor (services.tor).
          Может быть Android-tethering (IP телефона в WiFi сети), или
          upstream Tor через SSH/socat.
        '';
      };
      socksPort = lib.mkOption {
        type = lib.types.int;
        default = 9050;
        description = "SOCKS5 proxy port. Стандарт Tor = 9050.";
      };
      enableTdesktop = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Route Telegram Desktop через Tor SOCKS5. Если false — TDesktop
          запускается напрямую (no proxy). Полезно для отладки когда
          нужно TDesktop direct, но telega.el — через Tor.
        '';
      };
      enableTelegaServer = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Route telega-server (tdlib-bridge для telega.el) через Tor SOCKS5.
          Если false — telega.el ходит на Telegram напрямую.
        '';
      };
      extraArgs = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "Дополнительные args для tdesktop/telega-server wrappers.";
      };
    };
  };

  config = lib.mkIf cfg.useTor {
    environment.systemPackages = lib.optional enableTdesktopEffective tdesktop-launch
                              ++ lib.optional enableTelegaServerEffective telega-server-launch
                              ++ [ pkgs.torsocks ];

    # Systemd unit: boot-time Tor readiness check.
    systemd.services.pro-telegram-tor = proTelegramTorService;

    # Systemd user service: autostart tdesktop-tor (per-user, per session).
    systemd.user.services.tdesktop-tor = tdesktopUserService;

    # Подсказка в shell motd при login.
    environment.etc."pro/telegram-tor-mode.txt".text = lib.mkIf cfg.useTor ''
      Telegram через Tor:
        TDesktop:     ${if enableTdesktopEffective then "yes (через ${cfg.socksHost}:${toString cfg.socksPort})" else "no (direct)"}
        telega.el:    ${if enableTelegaServerEffective then "yes (через ${cfg.socksHost}:${toString cfg.socksPort})" else "no (direct)"}
      Проверить: scripts/check-tor-socks.sh --host ${cfg.socksHost} --port ${toString cfg.socksPort}
    '';
  };

}
