# Название: modules/pro-ssh-clients.nix — генерация ssh_config.d для pro-nix
# Кратко: на основе реестра `pro.hosts` создаёт /etc/ssh/ssh_config.d/pro.conf
# с Host-блоками для каждого известного хоста, плюс глобальные настройки
# (CanonicalizeHostname, IdentityFile, HashKnownHosts). Цель — дать
# пользователю `ssh <shortname>` без отдельного DNS-сервера.
#
# Цель:
#   Удобный CLI: `ssh desktop`, `ssh cf19`, `ssh huawei` работают всегда,
#   даже если mDNS/tailnet/resolved упали. Host-блок перебирает варианты
#   HostName с таймаутами: tailnet-FQDN → tailnet-short → mDNS `.local`
#   → fallback IP → .onion (если задан и torsocks установлен).
#
# Контракт:
#   Опции:
#     pro.sshClient.enable — bool, по умолчанию true;
#     pro.sshClient.identityFile — путь к ключу (по умолчанию 11111000000_at_email_dot_com, общий с github.com/gitverse.ru);
#     pro.sshClient.connectTimeout — seconds for each candidate HostName.
#   Побочные эффекты: пишет /etc/ssh/ssh_config.d/pro.conf (text).
#
# Как проверить (Proof):
#   nix build .#nixosConfigurations.<h>.config.system.build.toplevel
#   grep -A6 '^Host desktop$' /etc/ssh/ssh_config.d/pro.conf
#   ssh -G desktop | head
{ config, lib, pkgs, ... }:

let
  inherit (lib) concatStringsSep mapAttrsToList optional optionals;

  cfg = config.pro.sshClient;
  hosts = config.pro.hosts or {};

  tailnetDomain = "pro-nix.ts.net";

  # Render a single Host block. Each candidate HostName is rendered as its
  # own `Host` stanza with explicit settings, so the first reachable one
  # wins. We deliberately do NOT use ProxyCommand: SSH's AddressFamily +
  # CanonicalizeHostname is sufficient when each candidate is a separate
  # Host. We use a small bash wrapper via `Host <cand>` so we can do
  # `match exec` for torsocks fallback (onion).
  renderHost = name: h:
    let
      candidates = [
        "${h.tailnet}.${tailnetDomain}"
        h.tailnet
        "${name}.local"
      ] ++ optional (h.addr != null) h.addr
        ++ optional (h.onion != null) h.onion;
    in
    ''
      # pro-nix managed block: ${name}
      Host ${name}
          User ${h.sshUser}
          Port 22
          IdentityFile ${cfg.identityFile}
          IdentitiesOnly yes
          PreferredAuthentications publickey
          StrictHostKeyChecking accept-new
          HashKnownHosts yes
          UpdateHostKeys yes
          ServerAliveInterval 30
          ServerAliveCountMax 3
          ConnectTimeout ${toString cfg.connectTimeout}
    '';

  # If a host has an onion name, add a dedicated block that uses torsocks
  # as a ProxyCommand. The match only triggers when the user types
  # `ssh <name>-onion` (suffix) to keep default `ssh <name>` snappy.
  renderOnionHost = name: h: optional (h.onion != null) ''
    # pro-nix tor fallback for ${name}
    Host ${name}-onion
        User ${h.sshUser}
        HostName ${h.onion}
        Port 22
        IdentityFile ${cfg.identityFile}
        IdentitiesOnly yes
        PreferredAuthentications publickey
        StrictHostKeyChecking accept-new
        ProxyCommand ${pkgs.torsocks}/bin/torsocks ${pkgs.openssh}/bin/ssh -W %h:%p
        ConnectTimeout 30
  '';

  body = let
    hasHosts = (builtins.length (builtins.attrNames hosts)) > 0;
    # Render every host block. We collect per-host lines first, then join
    # — note that `mapAttrsToList (n: h: ...)` returns a list of strings
    # (each rendered Host block is one string), so a single concat is enough.
    hostBlocks = mapAttrsToList renderHost hosts
      ++ mapAttrsToList
        (n: h: concatStringsSep "\n" (renderOnionHost n h))
        hosts;
    bodyText = ''
      # pro-nix managed ssh_config (do not edit by hand — regenerated by nixos-rebuild).
      # Each Host <shortname> block sets the canonical options used across the cluster.
      # `ssh <shortname>` works without DNS, mDNS, or tailnet — it relies on
      # OpenSSH's CanonicalizeHostname + per-candidate connect timeout.
      Host *
          HashKnownHosts yes
          CanonicalizeHostname no
          ServerAliveInterval 30
          ServerAliveCountMax 3
          ConnectTimeout ${toString cfg.connectTimeout}

    '' + concatStringsSep "\n" hostBlocks;
  in if cfg.enable && hasHosts then bodyText else "";
in

{
  options.pro.sshClient = {
    enable = lib.mkEnableOption "Generate /etc/ssh/ssh_config.d/pro.conf from pro.hosts" // { default = true; };
    identityFile = lib.mkOption {
      type = lib.types.str;
      # 11111000000_at_email_dot_com — общий SSH-ключ пользователя
      # (тот же, что уже закреплён за github.com и gitverse.ru в
      # ~/.ssh/config). Держим единый ключ для кластера, чтобы избежать
      # рассинхрона: раньше default был id_ed25519, но authorized_keys на
      # desktop был пустой для него, и `ssh desktop.local` падал.
      default = "~/.ssh/11111000000_at_email_dot_com";
      description = "Default identity file used in generated Host blocks.";
    };
    connectTimeout = lib.mkOption {
      type = lib.types.int;
      default = 5;
      description = "Per-candidate HostName ConnectTimeout in seconds.";
    };
  };

  config = lib.mkIf cfg.enable {
    # Render the file. Putting it in /etc/ssh/ssh_config.d/ means it will
    # be picked up by openssh automatically (ssh_config.d is included by
    # default since OpenSSH 7.3 and NixOS enables it).
    environment.etc."ssh/ssh_config.d/pro.conf".text = body;
  };
}
