# Название: modules/pro-telegram.nix — Telegram Desktop + telega (Emacs) через Tor
# Summary (EN): Telegram clients (TDesktop, telega.el) routed через Tor SOCKS5
#                 когда Tor доступен на 127.0.0.1:9050 (стандартный local
#                 Tor daemon, либо upstream SOCKS5 от Android-tethering
#                 через WiFi/cellular).
#
# Цель:
#   Telegram MTProto протокол ходит напрямую (без proxy supportа в
#   mainline tdlib). Поэтому единственный practical path к анонимизации —
#   системный SOCKS5 proxy (Tor) через `torsocks`. Модуль:
#   1. Регистрирует `tdesktop-tor-launch` user-desktop entry, заменяющий
#      стандартный `telegram-desktop` на tor-conditional.
#   2. Регистрирует D-Bus / socket активацию для `telega-server` через
#      `telega-server-tor-launch` (через torsocks).
#   3. Обеспечивает `torsocks` пакет в `systemPackages`.
#   4. Опционально — даунгрейд до прямого подключения через
#      `pro.telegram.disableTor = true` (для отладки / non-Tor зон).
#
# Контракт:
#   Опции:
#     pro.telegram.useTor            — default true, основной switch.
#     pro.telegram.disableTor         — default false, explicit disable.
#     pro.telegram.socksHost/Port     — default 127.0.0.1:9050.
#     pro.telegram.enableTorService   — default true, проверять Tor на старте.
#   Побочные эффекты:
#     - Adds wrapper scripts `tdesktop-tor-launch` и `telega-server-tor-launch`
#       в `environment.systemPackages` (через writeShellScriptBin).
#     - Регистрирует `/etc/xdg/autostart/tdesktop-tor.desktop` (опционально).
#     - При `enableTorService = true` кладёт `/etc/systemd/system/`
#       сервис `pro-telegram-tor.service` (one-shot проверка Tor при boot).
#
# Как проверить:
#   ./scripts/check-tor-socks.sh                 # exit 0 = Tor OK
#   ./scripts/tdesktop-tor-launch.sh --check    # exit 0 = wrapped launch path
#   ./scripts/telega-server-tor-launch.sh --check
#
# Соответствие существующему:
#   - `services.tor` (pro-privacy.nix) стартует Tor с SOCKSPort=9050.
#   - Пользователь может вытащить WiFi на телефон и пользоваться его Tor
#     (Orbot/TorVPN), пробросив SOCKS5 через `socat` или `tun2socks` локально.
{ config, pkgs, lib, ... }:

let
  cfg = config.pro.telegram;

  # Wrapper scripts — генерируются в Nix store, доступны как
  # $PATH entries через environment.systemPackages.
  tdesktop-launch = pkgs.writeShellScriptBin "tdesktop-tor-launch" ''
    #!/usr/bin/env bash
    # Auto-generated by pro-telegram.nix. Wraps telegram-desktop,
    # routing через torsocks when Tor SOCKS5 is reachable.
    HOST="${PRO_TELEGRAM_TOR_HOST:-127.0.0.1}"
    PORT="${PRO_TELEGRAM_TOR_PORT:-9050}"
    exec ${./../scripts/check-tor-socks.sh} --host "$HOST" --port "$PORT" >/dev/null 2>&1 && \
      TOR=1 NON_TOR=0 || \
      TOR=0 NON_TOR=1
    if [ "$TOR" = "1" ] && command -v torsocks >/dev/null 2>&1; then
      exec torsocks telegram-desktop "$@"
    fi
    exec telegram-desktop "$@"
  '';

  telega-server-launch = pkgs.writeShellScriptBin "telega-server-tor-launch" ''
    #!/usr/bin/env bash
    HOST="${PRO_TELEGRAM_TOR_HOST:-127.0.0.1}"
    PORT="${PRO_TELEGRAM_TOR_PORT:-9050}"
    TG_PORT="${PRO_TELEGA_PORT:-6056}"
    exec ${./../scripts/check-tor-socks.sh} --host "$HOST" --port "$PORT" >/dev/null 2>&1 && \
      exec torsocks telega-server --forward=tcp:127.0.0.1:$TG_PORT:127.0.0.1:$TG_PORT "$@"
    exec telega-server --forward=tcp:127.0.0.1:$TG_PORT:127.0.0.1:$TG_PORT "$@"
  '';

  # Прокидываем environment.systemPackages
  pkgsForCfg = lib.optional cfg.useTor tdesktop-launch
             ++ lib.optional cfg.useTor telega-server-launch;

  # Systemd user service: перезапустить telega-server если Tor
  # переключился (была offline → стала available).
  proTelegramTorService = lib.mkIf cfg.enableTorService {
    description = "Ensure Tor SOCKS5 endpoint available before telega-server runs";
    wantedBy = [ "multi-user.target" ];
    after = [ "network-online.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${./../scripts/check-tor-socks.sh} -v";
    };
  };
in {

  options = {
    pro.telegram = {
      useTor = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Route Telegram clients (TDesktop, telega.el) через Tor SOCKS5
          когда Tor доступен. Fallback на direct connect если Tor
          недоступен.
        '';
      };
      enableTorService = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Создать systemd unit `pro-telegram-tor.service` который
          проверяет Tor при boot (one-shot). Полезно для boot-time
          readiness-check, не зависит от Telegram services.
        '';
      };
      socksHost = lib.mkOption {
        type = lib.types.str;
        default = "127.0.0.1";
        description = ''
          SOCKS5 proxy host. По умолчанию — локальный Tor (services.tor).
          Может быть Android-tethering (IP телефона в WiFi сети), или
          upstream Tor через SSH/socat.
        '';
      };
      socksPort = lib.mkOption {
        type = lib.types.int;
        default = 9050;
        description = "SOCKS5 proxy port. Стандарт Tor = 9050.";
      };
      extraArgs = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "Дополнительные args для tdesktop/telega-server wrappers.";
      };
    };
  };

  config = lib.mkIf cfg.useTor {
    environment.systemPackages = [
      tdesktop-launch
      telega-server-launch
      pkgs.torsocks
    ];

    # Systemd unit: проверка Tor при boot.
    systemd.services.pro-telegram-tor = proTelegramTorService;

    # Подсказка в shell motd при login (если Tor отключен в zone).
    environment.etc."pro/telegram-tor-mode.txt".text = lib.mkIf cfg.useTor ''
      Telegram через Tor: ${if cfg.socksHost == "127.0.0.1" then "local Tor daemon" else "remote proxy (${cfg.socksHost}:${toString cfg.socksPort})"}
      Проверить: scripts/check-tor-socks.sh
    '';
  };

}
