;; Autogenerated by scripts/regenerate-provided-packages.el
;; Source: /home/az/pro-nix/nix/provided-packages.nix

(setq pro-packages-provided-by-nix '(
  magit consult vertico orderless marginalia gptel consult-dash dash-docs
  consult-eglot consult-yasnippet corfu cape kind-icon avy expand-region
  yasnippet projectile treemacs consult-projectile elfeed eglot
  rainbow-delimiters nix-mode mmm-mode org vterm ace-window
  ;; Additional UI & integration packages we prefer to provide via Nix
  agent-shell treemacs-icons-dired all-the-icons nerd-icons
  nerd-icons-completion nerd-icons-ibuffer all-the-icons-completion))

(provide 'provided-packages)
