;; Autogenerated from emacs/core.nix (pro.emacs.providedPackages)
;; via home-manager activation. Keep in sync manually for dev environments.

(setq pro-packages-provided-by-nix '(ace-window acp agent-shell acapella all-the-icons atlas avy cape consult consult-dash consult-eglot consult-projectile consult-yasnippet corfu dash-docs eglot elfeed expand-region gptel kind-icon magit marginalia mmm-mode nerd-icons nix-mode ob-mermaid orderless org projectile rainbow-delimiters tao-theme shaoline telega treemacs treemacs-icons-dired undo-tree vertico vterm yasnippet ))

(provide 'provided-packages)
