;; Autogenerated from emacs/core.nix (pro.emacs.providedPackages)
;; via home-manager activation. Keep in sync manually for dev environments.

(setq pro-packages-provided-by-nix '(ace-window acp agent-shell acapella all-the-icons atlas avy cape consult consult-dash consult-eglot consult-projectile consult-yasnippet corfu dash-docs docker eglot elfeed emcp expand-region gptel haskell-mode haskell-snippets kind-icon magit marginalia markdown-mode mmm-mode nerd-icons nerd-icons-ibuffer nerd-icons-completion nix-mode ob-mermaid orderless org projectile rainbow-delimiters tao-theme shaoline telega transient treemacs treemacs-icons-dired undo-tree vertico vertico-sort vterm yasnippet ))

(provide 'provided-packages)
