;; Русский: комментарии и пояснения оформлены в стиле учебника
;;; pro-packages.el --- prompt-and-install package flow -*- lexical-binding: t; -*-
;; Minimal engine for prompt-and-install packages when not provided by Nix.

(require 'package)
(require 'subr-x)

(defvar pro-packages-decisions-file
  (expand-file-name "decisions.el" (expand-file-name ".config/emacs/" (getenv "HOME")))
  "User decisions file (alist of (pkg . decision)).")

(defvar pro-packages-decisions nil
  "Alist of package decisions: (pkg . (always|never)).")

(defvar pro-packages--refreshed nil
  "Non-nil once package-archives have been refreshed in this session.")

(defun pro-packages--load-decisions ()
  "Load decisions from `pro-packages-decisions-file` if present." 
  (when (file-exists-p pro-packages-decisions-file)
    (condition-case _err
        (load-file pro-packages-decisions-file)
      (error (message "[pro-packages] failed to load decisions")))))

(defun pro-packages--save-decisions ()
  "Persist `pro-packages-decisions` into `pro-packages-decisions-file` atomically." 
  (let ((dir (file-name-directory pro-packages-decisions-file)))
    (unless (file-directory-p dir) (make-directory dir t)))
  (with-temp-file (concat pro-packages-decisions-file ".tmp")
    (prin1 `(setq pro-packages-decisions ',pro-packages-decisions) (current-buffer)))
  (condition-case _err
      (rename-file (concat pro-packages-decisions-file ".tmp") pro-packages-decisions-file t)
    (error (message "[pro-packages] failed to save decisions"))))

(defun pro--package-provided-p (pkg)
  "Return non-nil if PKG is provided by Nix or already installed.
Checks `pro-packages-provided-by-nix` (generated by Nix), `package-installed-p`, and `locate-library'."
  ;; Prefer actual availability checks first (installed or on load-path).
  ;; If those fail, fall back to the Nix-provided list as an advisory
  ;; signal. The previous order could short-circuit on the Nix list and
  ;; incorrectly claim a package was available when it wasn't on
  ;; `load-path` — preventing fallback install attempts.
  (or (package-installed-p pkg)
      (locate-library (symbol-name pkg))
      (and (boundp 'pro-packages-provided-by-nix)
           (memq pkg pro-packages-provided-by-nix))))

(defun pro-packages--ask-user (pkg)
  "Prompt the user for how to handle missing PKG.
Return symbol: 'install, 'always, 'never or 'cancel." 
  (let ((prompt (format "Package %s is not provided by Nix. Install from MELPA? [i]nstall/[a]lways/[s]kip/[c]ancel: " pkg)))
    (pcase (read-char-choice prompt '(?i ?a ?s ?c))
      (?i 'install)
      (?a 'always)
      (?s 'never)
      (?c 'cancel))))

(defun pro-packages--do-install (pkg)
  "Install PKG via package.el. Refresh archives once per session if needed.
Return t on success." 
  (unless pro-packages--refreshed
    (condition-case _e
        (progn (package-refresh-contents) (setq pro-packages--refreshed t))
      (error (message "[pro-packages] failed to refresh package archives"))))
  (condition-case err
      (progn
        (package-install pkg)
        (message "[pro-packages] installed %s" pkg)
        t)
    (error (message "[pro-packages] failed to install %s: %s" pkg err) nil)))

(defun pro-packages--maybe-install (pkg &optional allow-melpa)
  "Ensure PKG is available. If missing and ALLOW-MELPA is non-nil, prompt-and-install.
Return t if PKG is now available (installed or provided)." 
  (unless (pro--package-provided-p pkg)
    (when allow-melpa
      (pro-packages--load-decisions)
       (let* ((decision (alist-get pkg pro-packages-decisions))
              ;; Default to auto-install enabled. This makes the pro profile
              ;; more user-friendly out of the box: when PRO_PACKAGES_AUTO_INSTALL
              ;; is not set we treat it as enabled so missing packages are
              ;; installed automatically. Users can still override by setting
              ;; PRO_PACKAGES_AUTO_INSTALL=0 in their environment.
              (auto-env (string= (or (getenv "PRO_PACKAGES_AUTO_INSTALL") "1") "1")))
        (cond
         ((eq decision 'always)
          (when (pro-packages--do-install pkg) (setq decision 'installed) t))
         ((eq decision 'never) nil)
         (t
          ;; If the environment requests auto-install, treat it as an override
          ;; and perform noninteractive installs. This is useful for CI/image builds
          ;; where prompts would otherwise block the run.
          (when auto-env
            (message "[pro-packages] PRO_PACKAGES_AUTO_INSTALL=1: auto-installing %s" pkg))
          (if (or noninteractive auto-env)
              (if auto-env
                  (pro-packages--do-install pkg)
                (message "[pro-packages] noninteractive: skipping install of %s" pkg)
                nil)
            (pcase (pro-packages--ask-user pkg)
              ('install (pro-packages--do-install pkg))
              ('always (push (cons pkg 'always) pro-packages-decisions)
                       (pro-packages--save-decisions)
                       (pro-packages--do-install pkg))
              ('never (push (cons pkg 'never) pro-packages-decisions)
                     (pro-packages--save-decisions) nil)
              ('cancel nil)))))))))

(provide 'pro-packages)

;;; pro-packages.el ends here
