;; Regenerate provided-packages.el from nix/provided-packages.nix using Emacs Lisp
;; Usage: emacs --batch -Q -l scripts/regenerate-provided-packages.el

(require 'subr-x)

(let* ((repo (expand-file-name ".." (file-name-directory (or load-file-name buffer-file-name))))
       (nix-file (expand-file-name "nix/provided-packages.nix" repo))
       (out-file (expand-file-name "emacs/base/provided-packages.el" repo)))
  (unless (file-readable-p nix-file)
    (error "nix file not found: %s" nix-file))
  (with-temp-buffer
    (insert-file-contents nix-file)
    (goto-char (point-min))
    (let ((pkg-list '()))
      ;; Use a regexp that matches `pkgs.emacsPackages.NAME` and capture NAME.
      ;; In an Emacs Lisp string backslashes must be escaped, so we use
      ;; "pkgs\\.emacsPackages\\.\\([A-Za-z0-9_-]+\\)".
      (while (re-search-forward "pkgs\\.emacsPackages\\.\\([A-Za-z0-9_-]+\\)" nil t)
        (push (match-string 1) pkg-list))
      (setq pkg-list (nreverse (delete-dups pkg-list)))
      (with-temp-file out-file
        (insert ";; Autogenerated by scripts/regenerate-provided-packages.el\n")
        (insert (format ";; Source: %s\n\n" nix-file))
        (insert "(setq pro-packages-provided-by-nix '(")
        (dolist (p pkg-list)
          (insert (format "%s " p)))
        (insert "))\n\n")
      (insert "(provide 'provided-packages)\n"))
    (message "wrote %s with %d packages" out-file (length pkg-list)))))
