;; Generate Emacs Lisp file listing packages provided by Nix
;; Usage: emacs --batch -l scripts/generate-provided-packages.el --eval '(generate-provided-packages "nix/provided-packages.nix" "~/.config/emacs/provided-packages.el")'

(require 'subr-x)

(defun generate-provided-packages (nix-file out-file)
  "Extract Emacs package names from NIX-FILE and write OUT-FILE.

The function looks for the literal block starting with
`emacsPackages = [` and ending with `];`, then extracts identifiers
of the form `pkgs.emacsPackages.NAME`. It writes an Emacs Lisp file
that sets `pro-packages-provided-by-nix` to the list of NAME symbols.
Errors if the expected markers are not found.
"
  (unless (file-exists-p nix-file)
    (error "nix file not found: %s" nix-file))
  (with-temp-buffer
    (insert-file-contents nix-file)
    (goto-char (point-min))
    (let ((begin (search-forward "emacsPackages = [" nil t)))
      (unless begin (error "cannot find emacsPackages array in %s" nix-file))
      (let ((start (point)))
        (unless (search-forward "];" nil t)
          (error "cannot find end of emacsPackages array in %s" nix-file))
        (let* ((s (buffer-substring-no-properties start (match-beginning 0)))
               (lines (split-string s "\n" t))
               (out '()))
          (dolist (ln lines)
            (when (string-match "pkgs\.emacsPackages\.\([A-Za-z0-9_-]+\)" ln)
              (push (match-string 1 ln) out)))
          (setq out (nreverse out))
          (with-temp-file out-file
            (insert ";; Autogenerated by scripts/generate-provided-packages.el\n")
            (insert (format ";; Source: %s\n\n" nix-file))
            (insert "(setq pro-packages-provided-by-nix '(")
            (dolist (p out)
              (insert (format "%s " p)))
            (insert "))\n"))
          (message "wrote %s with %d packages" out-file (length out))))))

)

(provide 'generate-provided-packages)
