#!/usr/bin/env bash
set -euo pipefail

# Generate emacs/base/provided-packages.el from nix/provided-packages.nix
NIX=nix/provided-packages.nix
OUT=emacs/base/provided-packages.el

if [ ! -f "$NIX" ]; then
  echo "nix file not found: $NIX" >&2
  exit 1
fi

pkgs=$(rg -o "pkgs\.emacsPackages\.[A-Za-z0-9_-]+" "$NIX" | sed -E 's/.*\.//g' | sort -u)

mkdir -p "$(dirname "$OUT")"
{
  echo ";; Autogenerated by scripts/generate-provided-packages.sh"
  echo ";; Source: $NIX"
  echo
  printf "(setq pro-packages-provided-by-nix '("
  for p in $pkgs; do
    printf "%s " "$p"
  done
  printf "))\n\n"
  echo "(provide 'provided-packages)"
} > "$OUT"

echo "wrote $OUT with $(echo "$pkgs" | wc -w) packages"
