;; Generate Emacs Lisp file listing packages provided by Nix
;; Usage: emacs --batch -l scripts/generate-provided-packages.el --eval '(generate-provided-packages "nix/provided-packages.nix" "~/.config/emacs/provided-packages.el")'

(require 'subr-x)

(defun generate-provided-packages (nix-file &optional out-file)
  "Extract Emacs package names from NIX-FILE and write OUT-FILE.

The function looks for the literal block starting with
`emacsPackages = [` and ending with `];`, then extracts identifiers
of the form `pkgs.emacsPackages.NAME`. It writes an Emacs Lisp file
that sets `pro-packages-provided-by-nix` to the list of NAME symbols.
If OUT-FILE is nil, prefer ~/.config/emacs/provided-packages.el when
writable, otherwise fall back to the repository file emacs/base/provided-packages.el.
"
  (unless (file-exists-p nix-file)
    (error "nix file not found: %s" nix-file))
  (let* ((user-out (expand-file-name "provided-packages.el"
                                     (expand-file-name ".config/emacs/" (getenv "HOME"))))
         (repo-root (or (and load-file-name (file-name-directory load-file-name))
                        (and buffer-file-name (file-name-directory buffer-file-name))
                        (expand-file-name ".." (file-name-directory (or (getenv "PWD") ".")))))
         (repo-out (expand-file-name "emacs/base/provided-packages.el" repo-root))
         (outfile (or out-file
                      (and (file-writable-p user-out) user-out)
                      (and (not (file-exists-p user-out)) (file-writable-p (file-name-directory user-out)) user-out)
                      repo-out)))
    (with-temp-buffer
      (insert-file-contents nix-file)
      (goto-char (point-min))
      (unless (search-forward "emacsPackages = [" nil t)
        (error "cannot find emacsPackages array in %s" nix-file))
      (let ((start (point)))
        (unless (search-forward "];" nil t)
          (error "cannot find end of emacsPackages array in %s" nix-file))
        (let* ((s (buffer-substring-no-properties start (match-beginning 0)))
               (lines (split-string s "\n" t))
               (pkg-list '()))
          (dolist (ln lines)
            (when (string-match "pkgs\.emacsPackages\.\([A-Za-z0-9_-]+\)" ln)
              (push (match-string 1 ln) pkg-list)))
          (setq pkg-list (nreverse pkg-list))
          (let ((out-dir (file-name-directory outfile)))
            (unless (and out-dir (file-directory-p out-dir))
              (make-directory out-dir t)))
          (with-temp-file outfile
            (insert ";; Autogenerated by scripts/generate-provided-packages.el\n")
            (insert (format ";; Source: %s\n\n" nix-file))
            (insert "(setq pro-packages-provided-by-nix '(")
            (dolist (p pkg-list)
              (insert (format "%s " p)))
            (insert "))\n"))
          (message "wrote %s with %d packages" outfile (length pkg-list))))))

(provide 'generate-provided-packages)
