#!/usr/bin/env python3
"""Extract defcustom / defgroup / defvar from emacs/base/modules/pro-*.el
   and write Zola-compatible Markdown files to both en/ and ru/ reference.
   Idempotent. Run via `just site-regen`.
"""
import re
import pathlib
import datetime
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR   = REPO / "emacs" / "base" / "modules"
SITE      = REPO / "site" / "content"

RE_GROUP = re.compile(
    r'\(defgroup\s+([A-Za-z0-9/_-]+)\s+nil\s+"((?:[^"\\]|\\.)*)"(?:\s+:group\s+\'([A-Za-z0-9/_-]+))?',
    re.MULTILINE,
)
RE_CUSTOM = re.compile(
    r'\(defcustom\s+([A-Za-z0-9/_-]+)\s+((?:[^"\\]|\\.)*?)\s+"((?:[^"\\]|\\.)*)"\s*(.*?)\)\s*\n',
    re.DOTALL,
)

def parse_lisp_value(s):
    s = s.strip()
    if s in ("t", "nil"):
        return "true" if s == "t" else "false"
    if s.startswith('"') and s.endswith('"'):
        return s[1:-1]
    if s.startswith("'"):
        return s[1:]
    if s.startswith("("):
        return s
    if re.match(r'^-?\d+(\.\d+)?$', s):
        return s
    return s

def format_default(s):
    v = parse_lisp_value(s)
    return f"`{v}`" if len(v) < 40 else f"`{v[:37]}…`"

T = {
    "en": {
        "title": "defcustom knobs",
        "tldr_tpl": "All ~{n} user-facing `defcustom` knobs across the pro-*.el modules, grouped by `defgroup`.",
        "intro": '<span class="gen-badge">auto-gen</span> Generated {date} from `emacs/base/modules/pro-*.el`.',
        "note": "> This page enumerates every `defcustom` exposed by the pro-*.el modules. It is regenerated by `just site-regen` from the actual Emacs source — if a knob is added or removed, this page changes with it.",
        "stats": "**Total knobs:** {n}  ·  **Total groups:** {g}  ·  **Files scanned:** {f}",
        "group_index": "## Group index",
        "header": "| Knob | Default | Description |",
        "sep": "|------|---------|-------------|",
        "defined_in": "*Defined in [`{file}`]({repo}/emacs/base/modules/{file}).*",
        "files_scanned": "## Files scanned",
    },
    "ru": {
        "title": "defcustom knobs",
        "tldr_tpl": "Все ~{n} пользовательских `defcustom` knob'ов в pro-*.el модулях, сгруппированных по `defgroup`.",
        "intro": '<span class="gen-badge">auto-gen</span> Сгенерировано {date} из `emacs/base/modules/pro-*.el`.',
        "note": "> Эта страница перечисляет каждый `defcustom`, экспонируемый pro-*.el модулями. Регенерируется через `just site-regen` из реального Emacs-исходника — если knob добавлен или удалён, эта страница меняется вместе.",
        "stats": "**Всего knob'ов:** {n}  ·  **Всего групп:** {g}  ·  **Файлов просканировано:** {f}",
        "group_index": "## Указатель групп",
        "header": "| Knob | Default | Описание |",
        "sep": "|------|---------|----------|",
        "defined_in": "*Определён в [`{file}`]({repo}/emacs/base/modules/{file}).*",
        "files_scanned": "## Просканированные файлы",
    },
}

def render(lang, customs, groups, files):
    L = []
    t = T[lang]
    L.append("+++")
    L.append(f'title = "{t["title"]}"')
    L.append('sort_by = "weight"')
    L.append('template = "page.html"')
    L.append("")
    L.append("[extra]")
    L.append(f'tldr = "{t["tldr_tpl"].format(n=len(customs), g=len(groups), f=len(files))}"')
    L.append("+++")
    L.append("")
    L.append(f"# {t['title']}")
    L.append("")
    L.append(t["intro"].format(date=datetime.date.today().isoformat()))
    L.append("")
    L.append(t["note"])
    L.append("")
    L.append(t["stats"].format(n=len(customs), g=len(groups), f=len(files)))
    L.append("")

    by_group = {}
    for c in customs:
        g = c["group"] or "(no group)"
        by_group.setdefault(g, []).append(c)

    L.append(t["group_index"])
    L.append("")
    for g in sorted(by_group.keys()):
        anchor = re.sub(r'[^a-z0-9-]+', '-', g.lower())
        L.append(f"* [`{g}`](#{anchor}) — {len(by_group[g])} knobs")
    L.append("")
    L.append("---")
    L.append("")

    repo = REPO.as_uri()
    for g in sorted(by_group.keys()):
        anchor = re.sub(r'[^a-z0-9-]+', '-', g.lower())
        L.append(f"## `{g}` {{ #{anchor} }}")
        L.append("")
        ginfo = groups.get(g, {})
        if ginfo:
            L.append(t["defined_in"].format(file=ginfo['file'], repo=repo))
            if ginfo.get("doc"):
                L.append("")
                L.append(f"> {ginfo['doc']}")
        L.append("")
        L.append(t["header"])
        L.append(t["sep"])
        for c in sorted(by_group[g], key=lambda x: x["name"]):
            doc = c["doc"].replace("|", "\\|").replace("\n", " ")
            if len(doc) > 200:
                doc = doc[:197] + "…"
            default = format_default(c["default"])
            L.append(f"| `{c['name']}` | {default} | {doc} |")
        L.append("")

    L.append("---")
    L.append("")
    L.append(t["files_scanned"])
    L.append("")
    for f in files:
        L.append(f"* `emacs/base/modules/{f.name}` — {len(re.findall(r'defcustom', f.read_text()))} defcustom")
    L.append("")
    return "\n".join(L)

def main():
    files = sorted(SRC_DIR.glob("pro-*.el"))
    groups = {}
    customs = []
    for f in files:
        text = f.read_text(errors="replace")
        for m in RE_GROUP.finditer(text):
            name, doc, parent = m.group(1), m.group(2), m.group(3)
            groups.setdefault(name, {"file": f.name, "doc": doc, "parent": parent})
        for m in RE_CUSTOM.finditer(text):
            name = m.group(1)
            default = m.group(2)
            doc = m.group(3)
            tail = m.group(4) or ""
            grp = None
            for gm in re.finditer(r':group\s+\'?([A-Za-z0-9/_-]+)', tail):
                grp = gm.group(1)
            customs.append({
                "name": name, "default": default.strip(), "doc": doc,
                "group": grp, "file": f.name,
            })

    for lang in ("en", "ru"):
        out = SITE / lang / "reference" / "defcustom.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(render(lang, customs, groups, files))
        print(f"wrote {out} ({len(customs)} knobs, {len(groups)} groups)")

if __name__ == "__main__":
    main()
