#!/usr/bin/env bash
# Regenerate every auto-gen page of the site.
# Idempotent. Run via `just site-regen` or directly.
set -euo pipefail
cd "$(cd "$(dirname "$0")/.." && pwd)"

echo "== site-regen =="

python3 scripts/site-extract-defcustom.py
python3 scripts/site-extract-keys.py
bash    scripts/site-extract-scripts.sh
python3 scripts/site-extract-submodules.py
python3 scripts/site-extract-tests.py
python3 scripts/site-extract-ci.py
python3 scripts/site-extract-ai-models.py

# options.md — re-use existing tools/generate-options-md.sh
# It writes to docs/analyse/options.md; we copy to site/content/{en,ru}/reference/options.md
# and rewrite the header for Zola.
if [ -x tools/generate-options-md.sh ]; then
  tools/generate-options-md.sh
  if [ -f docs/analyse/options.md ]; then
    for lang in en ru; do
      out="site/content/$lang/reference/options.md"
      if [ "$lang" = "en" ]; then
        title="NixOS options"
        tl_dr="Public NixOS options exposed by the pro-nix modules. Generated by tools/generate-options-md.sh from the 6 modules that declare mkOption."
        intro='<span class="gen-badge">auto-gen</span> Generated by `tools/generate-options-md.sh` from the modules that declare `mkOption`.'
        note='> Source modules: `pro-peer.nix`, `headscale.nix`, `emacs/home-manager.nix`, `opencode-tui.nix`, `zram-slice.nix`, `ssh-agent.nix`.'
      else
        title="NixOS-опции"
        tl_dr="Публичные NixOS-опции, экспонируемые pro-nix модулями. Сгенерировано tools/generate-options-md.sh из 6 модулей с mkOption."
        intro='<span class="gen-badge">auto-gen</span> Сгенерировано `tools/generate-options-md.sh` из модулей с `mkOption`.'
        note='> Исходные модули: `pro-peer.nix`, `headscale.nix`, `emacs/home-manager.nix`, `opencode-tui.nix`, `zram-slice.nix`, `ssh-agent.nix`.'
      fi
      {
        echo '+++'
        echo "title = \"$title\""
        echo 'sort_by = "weight"'
        echo 'template = "page.html"'
        echo ''
        echo '[extra]'
        echo "tldr = \"$tl_dr\""
        echo '+++'
        echo ''
        echo "# $title"
        echo ""
        echo "$intro"
        echo ""
        echo "$note"
        echo ""
        # strip the original "Назначение:" / "Сводка:" header lines
        tail -n +5 docs/analyse/options.md
      } > "$out"
      echo "wrote $out"
    done
  fi
fi

echo "== done =="
