#!/usr/bin/env bash
# scripts/telegram-tor-detect-host.sh
# Autodetect SOCKS5 endpoint для Telegram clients (tdesktop, telega-server).
#
# Логика (по убыванию приоритета):
#   1. Default gateway → :9050 (типично для Android-tethering с Orbot,
#      когда телефон раздаёт WiFi и пробрасывает SOCKS5 на своём LAN-IP).
#   2. Override из env PRO_TELEGRAM_TOR_HOST/PORT (если задан — приоритет
#      над autodetect; используется в systemd unit и при ручной настройке).
#   3. 127.0.0.1:9050 (локальный services.tor, прописанный в pro-privacy).
#   4. Empty → "no Tor", wrapper-скрипты упадут на direct connect.
#
# Режимы вывода:
#   --export              # shell-quoted `export PRO_TELEGRAM_TOR_HOST=…
#                         #       export PRO_TELEGRAM_TOR_PORT=…`
#   --env-file=PATH       # записать в файл KEY=VALUE (для systemd EnvironmentFile)
#   --json                # {"host":"…","port":…,"source":"gateway|local|none"}
#   --check               # exit 0 если Tor найден, 1 — нет
#   --debug               # печатать reasoning в stderr
#   (по умолчанию без флага — печатает host:port в stdout)
#
# Используется из:
#   - modules/pro-telegram.nix (systemd EnvironmentFile generation)
#   - modules/pro-telegram.nix (wrappers tdesktop-tor-launch, telega-server-tor-launch)
#
# Зависимости: `ip` (iproute2), bash, scripts/check-tor-socks.sh рядом.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

OUTPUT_MODE="plain"
ENV_FILE=""
DEBUG=0
FORCE_OVERRIDE=0

log() { [ "$DEBUG" -eq 1 ] && echo "[telegram-tor-detect] $*" >&2 || true; }

usage() {
  sed -n '2,40p' "$0"
  exit "${1:-0}"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --export)       OUTPUT_MODE="export"; shift ;;
    --env-file=*)   ENV_FILE="${1#*=}"; OUTPUT_MODE="env-file"; shift ;;
    --json)         OUTPUT_MODE="json"; shift ;;
    --check)        OUTPUT_MODE="check"; shift ;;
    --debug)        DEBUG=1; shift ;;
    --override)     FORCE_OVERRIDE=1; shift ;;
    -h|--help)      usage 0 ;;
    *)              echo "Unknown arg: $1" >&2; usage 4 ;;
  esac
done

# Probe SOCKS5 on host:port using check-tor-socks.sh. Returns 0 if OK.
probe() {
  local host="$1" port="$2"
  "$SCRIPT_DIR/check-tor-socks.sh" --host "$host" --port "$port" >/dev/null 2>&1
}

# Возвращает default gateway IPv4 (первый в списке), пусто если нет.
default_gateway() {
  ip -4 route show default 2>/dev/null \
    | awk '{for (i=1; i<=NF; i++) if ($i == "via") {print $(i+1); exit}}'
}

detect() {
  # 1. Explicit override из env (наивысший приоритет).
  local override_host="${PRO_TELEGRAM_TOR_HOST:-}"
  local override_port="${PRO_TELEGRAM_TOR_PORT:-}"
  if [ "$FORCE_OVERRIDE" -eq 1 ] || [ -n "$override_host" ]; then
    if [ -z "$override_port" ]; then override_port="9050"; fi
    if probe "$override_host" "$override_port"; then
      log "using override $override_host:$override_port"
      printf 'override\t%s\t%s\n' "$override_host" "$override_port"
      return 0
    fi
    log "override $override_host:$override_port unreachable, falling through"
  fi

  # 2. Default gateway (Android-tethering с Orbot).
  local gw
  gw="$(default_gateway)"
  if [ -n "$gw" ] && [ "$gw" != "127.0.0.1" ]; then
    if probe "$gw" "9050"; then
      log "using gateway $gw:9050 (likely Orbot on tethering phone)"
      printf 'gateway\t%s\t%s\n' "$gw" "9050"
      return 0
    fi
    log "gateway $gw:9050 no SOCKS5"
  else
    log "no usable default gateway (gw=$gw)"
  fi

  # 3. Local services.tor fallback.
  if probe "127.0.0.1" "9050"; then
    log "using local tor 127.0.0.1:9050"
    printf 'local\t%s\t%s\n' "127.0.0.1" "9050"
    return 0
  fi

  # 4. No Tor.
  log "no Tor endpoint reachable"
  printf 'none\t%s\t%s\n' "" ""
  return 1
}

result="$(detect || true)"
source_kind="$(printf '%s' "$result" | cut -f1)"
host="$(printf '%s' "$result" | cut -f2)"
port="$(printf '%s' "$result" | cut -f3)"

case "$OUTPUT_MODE" in
  export)
    if [ -n "$host" ]; then
      printf 'export PRO_TELEGRAM_TOR_HOST=%q\n' "$host"
      printf 'export PRO_TELEGRAM_TOR_PORT=%q\n' "$port"
    else
      printf '# no Tor endpoint reachable\n'
    fi
    ;;
  env-file)
    if [ -z "$ENV_FILE" ]; then echo "--env-file=PATH required" >&2; exit 4; fi
    mkdir -p "$(dirname "$ENV_FILE")"
    if [ -n "$host" ]; then
      cat > "$ENV_FILE" <<EOF
# Auto-generated by telegram-tor-detect-host.sh
# source=$source_kind
PRO_TELEGRAM_TOR_HOST=$host
PRO_TELEGRAM_TOR_PORT=$port
PRO_TELEGRAM_TOR_SOURCE=$source_kind
EOF
      log "wrote $ENV_FILE ($source_kind $host:$port)"
    else
      cat > "$ENV_FILE" <<EOF
# Auto-generated by telegram-tor-detect-host.sh
# source=none (no Tor reachable)
PRO_TELEGRAM_TOR_HOST=
PRO_TELEGRAM_TOR_PORT=
PRO_TELEGRAM_TOR_SOURCE=none
EOF
      log "wrote $ENV_FILE (none)"
    fi
    ;;
  json)
    if [ -n "$host" ]; then
      printf '{"host":"%s","port":%s,"source":"%s"}\n' "$host" "$port" "$source_kind"
    else
      printf '{"host":null,"port":null,"source":"none"}\n'
    fi
    ;;
  check)
    [ -n "$host" ] && exit 0 || exit 1
    ;;
  *)
    if [ -n "$host" ]; then
      printf '%s:%s\n' "$host" "$port"
    else
      printf '\n'
    fi
    ;;
esac

exit 0
